# Generated by Django 3.2.6 on 2021-08-24 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductFinancial',
            new_name='Financial',
        ),
        migrations.RenameModel(
            old_name='ProductProperty',
            new_name='Property',
        ),
    ]
